### ISSUE TITLE
Migrate from react-router-dom to inertiajs

### ISSUE THREAD

**Issue by sntlln93** [sntlln93/clini#29]
## Why?
- Inertia has -allmost out of the box- support for modal based routes through [momentum-modal](https://github.com/lepikhinb/momentum-modal?tab=readme-ov-file#momentum-modal).
- It also has it's own data fetching library `useForm` and can recieve server data through props so **useQuery** is not needed anymore probably.
- No more `/api` routes.

## Checklist
- [x] Install `breeze`.
- [x] Remove `react-router-dom`.
- [x] Remove `AuthContext` and authentication logic as it will be handled by laravel natively.
- [ ] Install ```momentum-modal``` and add declaration file for it.
- [ ] Figure out how to return to dashboard when there isn't a previous route different than the modal's.
- [ ] Refactor routing, create pages for modal routes such as `CreatePatient` and `ShowAppointment`.
- [ ] Remove the use of api calls.

## {Reading|Watching} material
- https://codecourse.com/watch/modals-in-inertia
- https://inertiajs.com/how-it-works
- https://www.youtube.com/watch?v=XFmJfTzGqzY

## Notes
I've runned some test with an example app and ~I couldn't make it work~ `->render()` is missing from the docs' example. ~I thing Inertia SSR maybe causing some issues~. Also, I couldn't find a proper example on react typescript so I need to create the declaration file for this package.

**Comment by sntlln93** [comment]
I'll hold this impulse for now. Let's finish this before refactoring the hole codebase.
