### ISSUE TITLE
Roadmap of next features

### ISSUE THREAD

**Issue by sntlln93** [sntlln93/clini#35]
- [ ] Reports
- [ ] Clinical history
- [ ] Lab/imagery results
- [ ] #38
- [ ] Online payments through Mercado Pago
- [ ] Web/mobile application for patients
- [ ] High Tier plan API to create integrations between customer's and clini's infractructure.
- [ ] Billing module: AFIP integration 
- [ ] Notify customers through Whatsapp/SMS
